// Sample data generation and initialization
// This file seeds the app with realistic sample data

import { Company, POC } from './company-storage';

// Generate UUIDs for consistent references
const generateId = () => crypto.randomUUID();

// Pre-generated IDs for cross-referencing
export const SAMPLE_IDS = {
    // Owners
    txdot: generateId(),
    ladotd: generateId(),
    okdot: generateId(),
    // Contractors
    gilchrist: generateId(),
    abcPaving: generateId(),
    southernAsphalt: generateId(),
    // Inspectors
    qualityInspection: generateId(),
    gulfCoast: generateId(),
    // Employees - Admins/PMs
    barryBoothe: generateId(),
    bobbyEvans: generateId(),
    paigeLandrum: generateId(),
    // Supervisors/Foremen
    santiagoRamos: generateId(),
    miltonMolina: generateId(),
    // Workers
    joseAmaya: generateId(),
    henryRamos: generateId(),
    hosniEscalante: generateId(),
    axelBarahona: generateId(),
    dylanLeon: generateId(),
    nekoPoland: generateId(),
    rubenOsorio: generateId(),
    mikeWilson: generateId(), // Kept existing
    steveJohnson: generateId(), // Kept existing
    tylerDavis: generateId(), // Kept existing
    joseMartinez: generateId(), // Kept existing
    davidBrown: generateId(), // Kept existing
    chrisTaylor: generateId(), // Kept existing
    // Projects
    la106: generateId(),
    us62: generateId(),
};

export const SAMPLE_OWNERS: Company[] = [
    {
        id: SAMPLE_IDS.txdot,
        name: 'TxDOT',
        address: '125 E. 11th Street',
        city: 'Austin',
        state: 'TX',
        zip: '78701',
        phone: '(512) 463-8585',
        email: 'info@txdot.gov',
        website: 'https://www.txdot.gov',
        isActive: true,
        pocs: [
            {
                id: generateId(),
                name: 'John Manager',
                title: 'Project Manager',
                email: 'john.manager@txdot.gov',
                phone: '(512) 463-8001',
                secondaryPhone: '',
                linkedInUrl: '',
                notes: 'Primary contact for highway projects',
                isActive: true,
            },
            {
                id: generateId(),
                name: 'Sarah Engineer',
                title: 'Senior Engineer',
                email: 'sarah.engineer@txdot.gov',
                phone: '(512) 463-8002',
                secondaryPhone: '(512) 555-1234',
                linkedInUrl: 'https://linkedin.com/in/sarahengineer',
                notes: '',
                isActive: true,
            },
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.ladotd,
        name: 'LA DOTD',
        address: '1201 Capitol Access Road',
        city: 'Baton Rouge',
        state: 'LA',
        zip: '70802',
        phone: '(225) 379-1200',
        email: 'info@dotd.la.gov',
        website: 'https://www.dotd.la.gov',
        isActive: true,
        pocs: [
            {
                id: generateId(),
                name: 'Mike Roberts',
                title: 'District Engineer',
                email: 'mike.roberts@la.gov',
                phone: '(225) 379-1201',
                secondaryPhone: '',
                linkedInUrl: '',
                notes: '',
                isActive: true,
            },
            {
                id: generateId(),
                name: 'Lisa Chen',
                title: 'Project Coordinator',
                email: 'lisa.chen@la.gov',
                phone: '(225) 379-1202',
                secondaryPhone: '',
                linkedInUrl: '',
                notes: 'Available Mon-Thu',
                isActive: true,
            },
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.okdot,
        name: 'Oklahoma DOT',
        address: '200 NE 21st Street',
        city: 'Oklahoma City',
        state: 'OK',
        zip: '73105',
        phone: '(405) 521-2631',
        email: 'info@odot.ok.gov',
        website: 'https://www.odot.org',
        isActive: true,
        pocs: [
            {
                id: generateId(),
                name: 'Tom Williams',
                title: 'Area Manager',
                email: 'tom.williams@odot.ok.gov',
                phone: '(405) 521-2632',
                secondaryPhone: '',
                linkedInUrl: '',
                notes: '',
                isActive: true,
            },
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

export const SAMPLE_CONTRACTORS: Company[] = [
    {
        id: SAMPLE_IDS.gilchrist,
        name: 'Gilchrist Construction',
        address: '4500 Highway 6 South',
        city: 'Houston',
        state: 'TX',
        zip: '77084',
        phone: '(281) 555-0100',
        email: 'info@gilchristconstruction.com',
        website: '',
        isActive: true,
        pocs: [
            {
                id: generateId(),
                name: 'Bill Gilchrist',
                title: 'Owner',
                email: 'bill@gilchristconstruction.com',
                phone: '(281) 555-0101',
                secondaryPhone: '',
                linkedInUrl: '',
                notes: 'Decision maker',
                isActive: true,
            },
            {
                id: generateId(),
                name: 'Dirk Fontenot',
                title: 'Superintendent',
                email: 'dfontenot@gilchrist.com',
                phone: '(318) 715-7302',
                secondaryPhone: '',
                linkedInUrl: '',
                notes: '',
                isActive: true,
            },
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: generateId(), // James Hamilton
        name: 'James Hamilton Construction',
        address: '1000 Main St',
        city: 'Silver City',
        state: 'NM',
        zip: '88061',
        phone: '(575) 555-2000',
        email: 'info@jameshamilton.com',
        website: '',
        isActive: true,
        pocs: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: generateId(), // Barriere
        name: 'Barriere Construction',
        address: '1234 River Rd',
        city: 'Baton Rouge',
        state: 'LA',
        zip: '70802',
        phone: '(225) 555-3000',
        email: 'info@barriere.com',
        website: '',
        isActive: true,
        pocs: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

export const SAMPLE_INSPECTORS: Company[] = [
    {
        id: SAMPLE_IDS.gulfCoast, // Swapped to match ID
        name: 'LA DOTD Inspection Division',
        address: '1201 Capitol Access Road',
        city: 'Baton Rouge',
        state: 'LA',
        zip: '70802',
        phone: '(225) 379-1234',
        email: 'inspection@la.gov',
        website: '',
        isActive: true,
        pocs: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.qualityInspection, // Swapped to match ID
        name: 'TxDOT Inspection Services',
        address: '125 E. 11th Street',
        city: 'Austin',
        state: 'TX',
        zip: '78701',
        phone: '(512) 463-5678',
        email: 'inspection@txdot.gov',
        website: '',
        isActive: true,
        pocs: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: generateId(),
        name: 'Quality Inspection Services',
        address: '789 Tech Park Drive',
        city: 'Austin',
        state: 'TX',
        zip: '78758',
        phone: '(512) 555-0400',
        email: 'info@qualityinspection.com',
        website: 'https://www.qualityinspection.com',
        isActive: true,
        pocs: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: generateId(),
        name: 'Gulf Coast Inspectors',
        address: '321 Harbor View',
        city: 'Baton Rouge',
        state: 'LA',
        zip: '70802',
        phone: '(225) 555-0500',
        email: 'info@gulfcoastinspectors.com',
        website: '',
        isActive: true,
        pocs: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];


export const SAMPLE_EMPLOYEES_PLACEHOLDER = []; // Moved below




export const SAMPLE_LOOKUP_VALUES = {
    project_status_types: [
        { id: generateId(), name: 'Open', isActive: true },
        { id: generateId(), name: 'Tentative', isActive: true },
        { id: generateId(), name: 'Closed', isActive: true },
        { id: generateId(), name: 'Canceled', isActive: true },
    ],
    contract_status_types: [
        { id: generateId(), name: 'Signed', isActive: true },
        { id: generateId(), name: 'Not Signed', isActive: true },
        { id: generateId(), name: 'Under Processing', isActive: true },
    ],
    shift_types: [
        { id: generateId(), name: 'Day', isActive: true },
        { id: generateId(), name: 'Night', isActive: true },
    ],
    warehouse_locations: [
        { id: generateId(), name: 'Arlington', isActive: true },
        { id: generateId(), name: 'Baton Rouge', isActive: true },
        { id: generateId(), name: 'Houston', isActive: true },
        { id: generateId(), name: 'OK City', isActive: true },
    ],
    asphalt_mix_types: [
        { id: generateId(), name: 'Type B', isActive: true },
        { id: generateId(), name: 'Type C', isActive: true },
        { id: generateId(), name: 'Type D', isActive: true },
    ],
    oil_types: [
        { id: generateId(), name: 'PG 64', isActive: true },
        { id: generateId(), name: 'PG 70', isActive: true },
        { id: generateId(), name: 'PG 76', isActive: true },
        { id: generateId(), name: 'Custom', isActive: true },
    ],
    oil_grades: [
        { id: generateId(), name: 'PG64-22', isActive: true },
        { id: generateId(), name: 'PG70-22', isActive: true },
        { id: generateId(), name: 'PG76-20', isActive: true },
        { id: generateId(), name: 'PG76-22', isActive: true },
    ],
    tack_coat_types: [
        { id: generateId(), name: 'Emulsion', isActive: true },
        { id: generateId(), name: 'Trackless', isActive: true },
        { id: generateId(), name: 'Hot Applied', isActive: true },
        { id: generateId(), name: 'Jebro', isActive: true },
        { id: generateId(), name: 'UF', isActive: true },
        { id: generateId(), name: 'PG67', isActive: true },
        { id: generateId(), name: 'PG70', isActive: true },
        { id: generateId(), name: 'PG76', isActive: true },
    ],
    uom_types: [
        { id: generateId(), name: 'SY', isActive: true },
        { id: generateId(), name: 'RL', isActive: true },
        { id: generateId(), name: 'EA', isActive: true },
        { id: generateId(), name: 'DY', isActive: true },
        { id: generateId(), name: 'GL', isActive: true },
        { id: generateId(), name: 'LF', isActive: true },
        { id: generateId(), name: 'LBS', isActive: true },
    ],
    high_grade_types: [
        { id: generateId(), name: 'SMA', isActive: true },
        { id: generateId(), name: 'SUPERPAVE', isActive: true },
    ],
    employee_classes: [
        { id: generateId(), name: 'Class A', isActive: true },
        { id: generateId(), name: 'Class B', isActive: true },
        { id: generateId(), name: 'Class C', isActive: true },
    ],
    employee_crafts: [
        { id: generateId(), name: 'Installer', isActive: true },
        { id: generateId(), name: 'Operator', isActive: true },
        { id: generateId(), name: 'Driver', isActive: true },
        { id: generateId(), name: 'Laborer', isActive: true },
        { id: generateId(), name: 'Foreman', isActive: true },
    ],
    equipment_categories: [
        { id: generateId(), name: 'Tractor', isActive: true },
        { id: generateId(), name: 'Trailer', isActive: true },
        { id: generateId(), name: 'Truck', isActive: true },
        { id: generateId(), name: 'Van', isActive: true },
        { id: generateId(), name: 'Blower', isActive: true },
        { id: generateId(), name: 'Tools', isActive: true },
    ],
    van_truck_types: [
        { id: generateId(), name: "26' Penske van w/lift gate", isActive: true },
        { id: generateId(), name: "53' Dry van with lift gate", isActive: true },
        { id: generateId(), name: "53' Dry van no lift gate", isActive: true },
        { id: generateId(), name: 'Tandem axle tractor day cab', isActive: true },
        { id: generateId(), name: 'Tandem axle tractor sleeper', isActive: true },
        { id: generateId(), name: 'Stinger cord for lift gate', isActive: true },
    ],
    pipe_length_options: [
        { id: generateId(), name: "12.5' schedule 40 steel", isActive: true },
        { id: generateId(), name: "13.6' schedule 40 steel", isActive: true },
        { id: generateId(), name: "14' schedule 40 steel", isActive: true },
        { id: generateId(), name: "12.5' Floating pipe", isActive: true },
    ],
    tractor_types: [
        { id: generateId(), name: 'Kubota with rollers', isActive: true },
        { id: generateId(), name: 'Kubota with no rollers', isActive: true },
    ],
    project_types: [
        { id: generateId(), name: 'City', isActive: true },
        { id: generateId(), name: 'State', isActive: true },
        { id: generateId(), name: 'Private', isActive: true },
        { id: generateId(), name: 'Airport', isActive: true },
        { id: generateId(), name: 'County', isActive: true },
        { id: generateId(), name: 'Port', isActive: true },
        { id: generateId(), name: 'Other', isActive: true },
    ],
    submittal_status_types: [
        { id: generateId(), name: 'Approved', isActive: true },
        { id: generateId(), name: 'Pending', isActive: true },
        { id: generateId(), name: 'Not Approved', isActive: true },
    ],
    oil_source_options: [
        { id: generateId(), name: 'Tanker Required (Eddie)', isActive: true },
        { id: generateId(), name: 'IFI tack truck, requires Doug or Eddie', isActive: true },
        { id: generateId(), name: 'Contractor sprays & supplies oil', isActive: true },
        { id: generateId(), name: 'Contractor supplies oil only', isActive: true },
        { id: generateId(), name: 'Contractor supplies oil, IFI sprays', isActive: true },
        { id: generateId(), name: 'IFI sprays & supplies oil', isActive: true },
    ],
    // New lookup tables for Forms
    issue_types: [
        { id: generateId(), name: 'Weather Delay', isActive: true },
        { id: generateId(), name: 'Equipment Failure', isActive: true },
        { id: generateId(), name: 'Material Shortage', isActive: true },
        { id: generateId(), name: 'Safety Incident', isActive: true },
        { id: generateId(), name: 'Quality Issue', isActive: true },
        { id: generateId(), name: 'Schedule Change', isActive: true },
        { id: generateId(), name: 'Customer Request', isActive: true },
        { id: generateId(), name: 'Other', isActive: true },
    ],
    lane_types: [
        { id: generateId(), name: 'EB', isActive: true },
        { id: generateId(), name: 'WB', isActive: true },
        { id: generateId(), name: 'NB', isActive: true },
        { id: generateId(), name: 'SB', isActive: true },
        { id: generateId(), name: 'Left Lane', isActive: true },
        { id: generateId(), name: 'Right Lane', isActive: true },
        { id: generateId(), name: 'Center Lane', isActive: true },
        { id: generateId(), name: 'Shoulder', isActive: true },
    ],
    surface_types: [
        { id: generateId(), name: 'Milled', isActive: true },
        { id: generateId(), name: 'Levelup', isActive: true },
        { id: generateId(), name: 'Seal Coat', isActive: true },
    ],
    standby_reasons: [
        { id: generateId(), name: 'Standby Due to Customer', isActive: true },
        { id: generateId(), name: 'Demob Requested by Customer', isActive: true },
        { id: generateId(), name: 'Standby Due to Weather', isActive: true },
        { id: generateId(), name: 'Plant Breakdown', isActive: true },
        { id: generateId(), name: 'Lab Issues', isActive: true },
        { id: generateId(), name: 'Low Temperatures', isActive: true },
        { id: generateId(), name: 'Rain Delay', isActive: true },
    ],
};



export const SAMPLE_MATERIALS = [
    {
        id: generateId(),
        code: 'RG50-10',
        description: 'Roadglas 50-10',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[1].id,
        uomName: 'RL',
        manufacturer: 'Owens Corning',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'RG50-12.5',
        description: 'Roadglas 50-12.5',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[1].id,
        uomName: 'RL',
        manufacturer: 'Owens Corning',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'GP25-12.5',
        description: 'Grid Pavement 25-12.5',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[0].id,
        uomName: 'SY',
        manufacturer: 'TenCate',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'GP50-12.5',
        description: 'Grid Pavement 50-12.5',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[0].id,
        uomName: 'SY',
        manufacturer: 'TenCate',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'GP100-12.5',
        description: 'Grid Pavement 100-12.5',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[0].id,
        uomName: 'SY',
        manufacturer: 'TenCate',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'FG100',
        description: 'Fiberglass 100',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[5].id,
        uomName: 'LF',
        manufacturer: 'Owens Corning',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'FG200',
        description: 'Fiberglass 200',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[5].id,
        uomName: 'LF',
        manufacturer: 'Owens Corning',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'PT-High',
        description: 'PetroTac High Temp',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[1].id,
        uomName: 'RL',
        manufacturer: 'Propex',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'PT-Low',
        description: 'PetroTac Low Temp',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[1].id,
        uomName: 'RL',
        manufacturer: 'Propex',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'TruPave',
        description: 'TruPave Paving Mat',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[0].id,
        uomName: 'SY',
        manufacturer: 'Owens Corning',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'GlasGrid 8501',
        description: 'GlasGrid 8501 Detail Repair',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[1].id,
        uomName: 'RL',
        manufacturer: 'Saint-Gobain',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'GlasGrid 8511',
        description: 'GlasGrid 8511 Full Width',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[0].id,
        uomName: 'SY',
        manufacturer: 'Saint-Gobain',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'GlasPave 25',
        description: 'GlasPave 25 Paving Mat',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[0].id,
        uomName: 'SY',
        manufacturer: 'Saint-Gobain',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'GlasPave 50',
        description: 'GlasPave 50 Paving Mat',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[0].id,
        uomName: 'SY',
        manufacturer: 'Saint-Gobain',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'Petromat 4598',
        description: 'Petromat 4598 Nonwoven',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[0].id,
        uomName: 'SY',
        manufacturer: 'Propex',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'Petromat 4599',
        description: 'Petromat 4599 Reinforced',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[0].id,
        uomName: 'SY',
        manufacturer: 'Propex',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'Mirafi MPV500',
        description: 'Mirafi MPV500 Paving Fabric',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[0].id,
        uomName: 'SY',
        manufacturer: 'TenCate',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'Mirafi MPV700',
        description: 'Mirafi MPV700 Paving Fabric',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[0].id,
        uomName: 'SY',
        manufacturer: 'TenCate',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'Huesker HaTelit C',
        description: 'Huesker HaTelit C 40/17',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[0].id,
        uomName: 'SY',
        manufacturer: 'Huesker',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'ILG1002I',
        description: 'Intermediate Layer Grid 1002I',
        uomId: SAMPLE_LOOKUP_VALUES.uom_types[0].id,
        uomName: 'SY',
        manufacturer: 'Ind Fab',
        totalEstimatedQty: 0,
        totalEstimatedRolls: 0,
        isActive: true,
    },
];

export const SAMPLE_EQUIPMENT = [
    {
        id: generateId(),
        code: 'EQ-001',
        name: 'Ford F-250 Super Duty',
        category: SAMPLE_LOOKUP_VALUES.equipment_categories[2].name, // Truck
        categoryId: SAMPLE_LOOKUP_VALUES.equipment_categories[2].id,
        ownership: 'Owned' as const,
        status: 'Active' as const,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'EQ-002',
        name: 'GMC Sierra 1500',
        category: SAMPLE_LOOKUP_VALUES.equipment_categories[2].name, // Truck
        categoryId: SAMPLE_LOOKUP_VALUES.equipment_categories[2].id,
        ownership: 'Owned' as const,
        status: 'Active' as const,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'EQ-003',
        name: 'Kubota Tractor M7',
        category: SAMPLE_LOOKUP_VALUES.equipment_categories[0].name, // Tractor
        categoryId: SAMPLE_LOOKUP_VALUES.equipment_categories[0].id,
        ownership: 'Owned' as const,
        status: 'Active' as const,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'EQ-004',
        name: 'Flatbed Trailer 20ft',
        category: SAMPLE_LOOKUP_VALUES.equipment_categories[1].name, // Trailer
        categoryId: SAMPLE_LOOKUP_VALUES.equipment_categories[1].id,
        ownership: 'Owned' as const,
        status: 'Active' as const,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'EQ-005',
        name: 'Utility Trailer 12ft',
        category: SAMPLE_LOOKUP_VALUES.equipment_categories[1].name, // Trailer
        categoryId: SAMPLE_LOOKUP_VALUES.equipment_categories[1].id,
        ownership: 'Owned' as const,
        status: 'Active' as const,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'EQ-006',
        name: 'Asphalt Distributor Truck',
        category: SAMPLE_LOOKUP_VALUES.equipment_categories[2].name, // Truck
        categoryId: SAMPLE_LOOKUP_VALUES.equipment_categories[2].id,
        ownership: 'Owned' as const,
        status: 'Maintenance' as const,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'EQ-007',
        name: 'Walk-behind Roller',
        category: SAMPLE_LOOKUP_VALUES.equipment_categories[5].name, // Tools/Other (mapped to Tools for now)
        categoryId: SAMPLE_LOOKUP_VALUES.equipment_categories[5].id,
        ownership: 'Rented' as const,
        status: 'Active' as const,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'EQ-008',
        name: 'Billy Goat Blower',
        category: SAMPLE_LOOKUP_VALUES.equipment_categories[4].name, // Blower
        categoryId: SAMPLE_LOOKUP_VALUES.equipment_categories[4].id,
        ownership: 'Owned' as const,
        status: 'Active' as const,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'EQ-009',
        name: 'Little Wonder Blower',
        category: SAMPLE_LOOKUP_VALUES.equipment_categories[4].name, // Blower
        categoryId: SAMPLE_LOOKUP_VALUES.equipment_categories[4].id,
        ownership: 'Owned' as const,
        status: 'Active' as const,
        isActive: true,
    },
    {
        id: generateId(),
        code: 'EQ-010',
        name: 'Chevy Express Van',
        category: SAMPLE_LOOKUP_VALUES.equipment_categories[3].name, // Van
        categoryId: SAMPLE_LOOKUP_VALUES.equipment_categories[3].id,
        ownership: 'Owned' as const,
        status: 'Active' as const,
        isActive: true,
    },
];

export const SAMPLE_EMPLOYEES = [
    {
        id: SAMPLE_IDS.barryBoothe,
        employeeId: 'EMP001',
        name: 'Barry Boothe',
        role: 'Admin' as const,
        appRole: 'super-admin' as const,
        hasAppAccess: true,
        assignedProjects: [],
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[0].id,
        className: 'Class A',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[4].id,
        craftName: 'Foreman',
        email: 'bboothe@ifi.com',
        phone: '(225) 610-6263',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.bobbyEvans,
        employeeId: 'EMP002',
        name: 'Bobby Evans',
        role: 'Admin' as const,
        appRole: 'super-admin' as const,
        hasAppAccess: true,
        assignedProjects: [],
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[0].id,
        className: 'Class A',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[4].id,
        craftName: 'Foreman',
        email: 'bevans@ifi.com',
        phone: '(800) 543-5816',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.paigeLandrum,
        employeeId: 'EMP003',
        name: 'Paige Landrum',
        role: 'PM' as const,
        appRole: 'pm' as const,
        hasAppAccess: true,
        assignedProjects: [],
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[0].id,
        className: 'Class A',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[4].id,
        craftName: 'Foreman',
        email: 'plandrum@ifi.com',
        phone: '(225) 908-0780',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.santiagoRamos,
        employeeId: 'EMP004',
        name: 'Santiago Ramos',
        role: 'Supervisor' as const,
        appRole: 'supervisor' as const,
        hasAppAccess: true,
        assignedProjects: [],
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[0].id,
        className: 'Class A',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[0].id,
        craftName: 'Installer',
        email: 'sramos@ifi.com',
        phone: '(225) 555-1001',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.miltonMolina,
        employeeId: 'EMP005',
        name: 'Milton Molina',
        role: 'Lead' as const,
        appRole: 'lead' as const,
        hasAppAccess: true,
        assignedProjects: [],
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[1].id,
        className: 'Class B',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[0].id,
        craftName: 'Installer',
        email: 'mmolina@ifi.com',
        phone: '(225) 555-1002',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.joseAmaya,
        employeeId: 'EMP006',
        name: 'Jose Danilo Amaya',
        role: 'Worker' as const,
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[1].id,
        className: 'Class B',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[0].id,
        craftName: 'Installer',
        email: 'jamaya@ifi.com',
        phone: '(225) 555-1003',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.henryRamos,
        employeeId: 'EMP007',
        name: 'Henry David Ramos',
        role: 'Worker' as const,
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[1].id,
        className: 'Class B',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[1].id,
        craftName: 'Operator',
        email: 'hramos@ifi.com',
        phone: '(225) 555-1004',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.hosniEscalante,
        employeeId: 'EMP008',
        name: 'Hosni Escalante',
        role: 'Worker' as const,
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[1].id,
        className: 'Class B',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[0].id,
        craftName: 'Installer',
        email: 'hescalante@ifi.com',
        phone: '(225) 555-1005',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.axelBarahona,
        employeeId: 'EMP009',
        name: 'Axel Barahona Sanchez',
        role: 'Worker' as const,
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[2].id,
        className: 'Class C',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[3].id,
        craftName: 'Laborer',
        email: 'abarahona@ifi.com',
        phone: '(225) 555-1006',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.dylanLeon,
        employeeId: 'EMP010',
        name: 'Dylan Leon',
        role: 'Worker' as const,
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[2].id,
        className: 'Class C',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[3].id,
        craftName: 'Laborer',
        email: 'dleon@ifi.com',
        phone: '(225) 555-1007',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.nekoPoland,
        employeeId: 'EMP011',
        name: 'Neko Poland',
        role: 'Worker' as const,
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[2].id,
        className: 'Class C',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[2].id,
        craftName: 'Driver',
        email: 'npoland@ifi.com',
        phone: '(225) 555-1008',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.rubenOsorio,
        employeeId: 'EMP012',
        name: 'Ruben Osorio',
        role: 'Worker' as const,
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[2].id,
        className: 'Class C',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[3].id,
        craftName: 'Laborer',
        email: 'rosorio@ifi.com',
        phone: '(225) 555-1009',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.mikeWilson,
        employeeId: 'EMP013',
        name: 'Mike Wilson',
        role: 'Lead' as const,
        appRole: 'lead' as const,
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[1].id,
        className: 'Class B',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[0].id,
        craftName: 'Installer',
        email: 'mwilson@ifi.com',
        phone: '(225) 555-1010',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.steveJohnson,
        employeeId: 'EMP014',
        name: 'Steve Johnson',
        role: 'Worker' as const,
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[2].id,
        className: 'Class C',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[3].id,
        craftName: 'Laborer',
        email: 'sjohnson@ifi.com',
        phone: '(225) 555-1011',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.tylerDavis,
        employeeId: 'EMP015',
        name: 'Tyler Davis',
        role: 'Worker' as const,
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[2].id,
        className: 'Class C',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[3].id,
        craftName: 'Laborer',
        email: 'tdavis@ifi.com',
        phone: '(225) 555-1012',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.joseMartinez,
        employeeId: 'EMP016',
        name: 'Jose Martinez',
        role: 'Worker' as const,
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[1].id,
        className: 'Class B',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[0].id,
        craftName: 'Installer',
        email: 'jmartinez@ifi.com',
        phone: '(225) 555-1013',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.davidBrown,
        employeeId: 'EMP017',
        name: 'David Brown',
        role: 'Worker' as const,
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[2].id,
        className: 'Class C',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[3].id,
        craftName: 'Laborer',
        email: 'dbrown@ifi.com',
        phone: '(225) 555-1014',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: SAMPLE_IDS.chrisTaylor,
        employeeId: 'EMP018',
        name: 'Chris Taylor',
        role: 'Worker' as const,
        classId: SAMPLE_LOOKUP_VALUES.employee_classes[2].id,
        className: 'Class C',
        craftId: SAMPLE_LOOKUP_VALUES.employee_crafts[3].id,
        craftName: 'Laborer',
        email: 'ctaylor@ifi.com',
        phone: '(225) 555-1015',
        photo: null,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

// Initialize sample data in localStorage
export function initializeSampleData(forceReset = false) {
    if (typeof window === 'undefined') return;

    // Check if data already exists
    const hasOwners = localStorage.getItem('ifi_owners');
    // Using v6 now
    const hasEmployees = localStorage.getItem('ifi_employees_v7');

    if (!forceReset && hasOwners && hasEmployees) {
        console.log('Sample data already exists, skipping initialization');
        return;
    }

    console.log('Initializing sample data...');

    // Clear all data if force reset
    if (forceReset) {
        const keysToRemove = [
            'ifi_owners', 'ifi_contractors', 'ifi_inspectors',
            'ifi_employees_v4', 'ifi_employees_v5', 'ifi_employees_v6',
            'ifi_materials', 'ifi_equipment',
            'ifi_projects', 'ifi_timesheets', 'ifi_lookup_values',
            'ifi_standalone_contacts', 'ifi_company_profile',
            'ifi_material_usage_logs', 'ifi_issues_logs',
            'ifi_daily_field_reports', 'ifi_jha_forms', 'ifi_preconstruction_checklists'
        ];
        keysToRemove.forEach(key => localStorage.removeItem(key));
    }

    // Save companies
    localStorage.setItem('ifi_owners', JSON.stringify(SAMPLE_OWNERS));
    localStorage.setItem('ifi_contractors', JSON.stringify(SAMPLE_CONTRACTORS));
    localStorage.setItem('ifi_inspectors', JSON.stringify(SAMPLE_INSPECTORS));

    // Save employees
    localStorage.setItem('ifi_employees_v7', JSON.stringify(SAMPLE_EMPLOYEES));

    // Save materials
    localStorage.setItem('ifi_materials', JSON.stringify(SAMPLE_MATERIALS));

    // Save equipment
    localStorage.setItem('ifi_equipment', JSON.stringify(SAMPLE_EQUIPMENT));

    // Save lookup values
    localStorage.setItem('ifi_lookup_values', JSON.stringify(SAMPLE_LOOKUP_VALUES));

    // Create sample projects
    const sampleProjects = [
        {
            id: SAMPLE_IDS.la106,
            name: 'LA 106 Phase 3',
            epNumber: 'EP-2024-001',
            statusId: SAMPLE_LOOKUP_VALUES.project_status_types[0].id,
            statusName: 'Open',
            contractStatusId: SAMPLE_LOOKUP_VALUES.contract_status_types[0].id,
            contractStatusName: 'Signed',
            ownerId: SAMPLE_IDS.ladotd,
            ownerName: 'LA DOTD',
            ownerAddress: '1201 Capitol Access Road, Baton Rouge, LA 70802',
            ownerPocIds: [],
            contractorId: SAMPLE_IDS.gilchrist,
            contractorName: 'Gilchrist Construction',
            contractorAddress: '4500 Highway 6 South, Houston, TX 77084',
            contractorPocIds: [],
            inspectorId: SAMPLE_IDS.gulfCoast,
            inspectorName: 'Gulf Coast Inspectors',
            inspectorAddress: '321 Harbor View, Baton Rouge, LA 70802',
            inspectorPocIds: [],
            salespersonId: SAMPLE_IDS.barryBoothe,
            salespersonName: 'Barry Boothe',
            pmIds: [SAMPLE_IDS.paigeLandrum],
            supervisorIds: [SAMPLE_IDS.barryBoothe],
            leadIds: [SAMPLE_IDS.miltonMolina],
            workerIds: [SAMPLE_IDS.joseAmaya, SAMPLE_IDS.henryRamos, SAMPLE_IDS.hosniEscalante, SAMPLE_IDS.axelBarahona],
            streetAddress: 'LA Highway 106',
            county: 'Acadia Parish',
            city: 'Crowley',
            state: 'LA',
            zip: '70526',
            gpsStart: '30.22, -92.37',
            gpsEnd: '30.25, -92.35',
            estimatedStartDate: '2025-11-17',
            estimatedEndDate: '2025-11-20',
            estimatedDurationDays: 3,
            estimatedDateOnSite: '2025-11-17',
            shiftId: SAMPLE_LOOKUP_VALUES.shift_types[0].id,
            shiftName: 'Day',
            scheduleNotes: 'Weather dependent schedule',
            contractDocument: '',
            signedContract: '',
            materials: [
                {
                    id: generateId(),
                    materialId: SAMPLE_MATERIALS[19].id, // ILG1002I
                    description: SAMPLE_MATERIALS[19].description,
                    uom: SAMPLE_MATERIALS[19].uomName,
                    totalEstimatedQty: 2500,
                    totalEstimatedRolls: 10,
                },
            ],
            ownedEquipment: [
                SAMPLE_EQUIPMENT[0], // Kubota Tractor
                SAMPLE_EQUIPMENT[2], // Trailer
            ],
            thirdPartyEquipment: [],
            isDraft: false,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: SAMPLE_IDS.us62,
            name: 'US 62 Seagraves',
            epNumber: 'EP-2024-002',
            statusId: SAMPLE_LOOKUP_VALUES.project_status_types[1].id,
            statusName: 'Tentative',
            contractStatusId: SAMPLE_LOOKUP_VALUES.contract_status_types[2].id,
            contractStatusName: 'Under Processing',
            ownerId: SAMPLE_IDS.txdot,
            ownerName: 'TxDOT',
            ownerAddress: '125 E. 11th Street, Austin, TX 78701',
            ownerPocIds: [],
            contractorId: SAMPLE_CONTRACTORS[1].id, // James Hamilton
            contractorName: 'James Hamilton Construction',
            contractorAddress: '1000 Main St, Silver City, NM 88061',
            contractorPocIds: [],
            inspectorId: SAMPLE_INSPECTORS[1].id, // TxDOT Inspection
            inspectorName: 'TxDOT Inspection Services',
            inspectorAddress: '125 E. 11th Street, Austin, TX 78701',
            inspectorPocIds: [],
            salespersonId: SAMPLE_IDS.bobbyEvans,
            salespersonName: 'Bobby Evans',
            pmIds: [SAMPLE_IDS.paigeLandrum],
            supervisorIds: [SAMPLE_IDS.santiagoRamos],
            leadIds: [],
            workerIds: [SAMPLE_IDS.dylanLeon, SAMPLE_IDS.nekoPoland, SAMPLE_IDS.rubenOsorio],
            streetAddress: 'US Highway 62',
            county: 'Gaines County',
            city: 'Seagraves',
            state: 'TX',
            zip: '79359',
            gpsStart: '32.93, -102.55',
            gpsEnd: '32.95, -102.53',
            estimatedStartDate: '2025-12-15',
            estimatedEndDate: '2025-12-20',
            estimatedDurationDays: 5,
            estimatedDateOnSite: '2025-12-15',
            shiftId: SAMPLE_LOOKUP_VALUES.shift_types[0].id,
            shiftName: 'Day',
            scheduleNotes: '',
            contractDocument: '',
            signedContract: '',
            materials: [
                {
                    id: generateId(),
                    materialId: SAMPLE_MATERIALS[1].id, // RG50-12.5 Roadglas
                    description: SAMPLE_MATERIALS[1].description,
                    uom: SAMPLE_MATERIALS[1].uomName,
                    totalEstimatedQty: 5000,
                    totalEstimatedRolls: 5,
                },
                {
                    id: generateId(),
                    materialId: SAMPLE_MATERIALS[0].id, // RG50-10
                    description: SAMPLE_MATERIALS[0].description,
                    uom: SAMPLE_MATERIALS[0].uomName,
                    totalEstimatedQty: 2500,
                    totalEstimatedRolls: 5,
                },
            ],
            ownedEquipment: [],
            thirdPartyEquipment: [],
            isDraft: false,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    localStorage.setItem('ifi_projects', JSON.stringify(sampleProjects));

    // Create sample Material Usage Logs
    const sampleMaterialUsageLogs = [
        {
            id: generateId(),
            projectId: SAMPLE_IDS.la106,
            projectName: 'LA 106 Phase 3',
            date: '2025-11-18',
            stations: [
                {
                    id: generateId(),
                    fromStation: '327+00',
                    toStation: '283+15',
                    widthFt: 12,
                    sy: 528,
                    laneId: SAMPLE_LOOKUP_VALUES.lane_types[0].id,
                    laneName: 'EB',
                },
            ],
            materials: [
                {
                    id: generateId(),
                    materialId: SAMPLE_MATERIALS[19].id, // ILG1002I
                    materialCode: 'ILG1002I',
                    materialDescription: SAMPLE_MATERIALS[19].description,
                    fullRolls: 10,
                    halfRolls: 2,
                    fullRollArea: 242.98,
                    syInstalled: 2600,
                    overlapPercent: 5,
                    netSy: 2470,
                },
            ],
            tackCoatTypeId: SAMPLE_LOOKUP_VALUES.tack_coat_types[3].id, // Jebro
            tackCoatTypeName: 'Jebro',
            tackStartGallons: 500,
            tackEndGallons: 320,
            tackTotalGallons: 180,
            gridBeneath: true,
            gridOnTop: false,
            standbyReasonId: '',
            standbyReasonName: '',
            comments: 'Good install day, no issues.',
            status: 'approved' as const,
            totalSy: 528,
            totalNetSy: 2470,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            createdBy: 'Barry Boothe',
        },
        {
            id: generateId(),
            projectId: SAMPLE_IDS.us62,
            projectName: 'US 62 Seagraves',
            date: '2025-12-20',
            stations: [
                {
                    id: generateId(),
                    fromStation: '100+00',
                    toStation: '150+00',
                    widthFt: 10,
                    sy: 556,
                    laneId: SAMPLE_LOOKUP_VALUES.lane_types[1].id,
                    laneName: 'WB',
                },
            ],
            materials: [
                {
                    id: generateId(),
                    materialId: SAMPLE_MATERIALS[2].id,
                    materialCode: 'GP25-12.5',
                    materialDescription: SAMPLE_MATERIALS[2].description,
                    fullRolls: 5,
                    halfRolls: 0,
                    fullRollArea: 2500,
                    syInstalled: 12500,
                    overlapPercent: 10,
                    netSy: 11250,
                },
            ],
            tackCoatTypeId: SAMPLE_LOOKUP_VALUES.tack_coat_types[1].id,
            tackCoatTypeName: 'JEBRO',
            tackStartGallons: 300,
            tackEndGallons: 200,
            tackTotalGallons: 100,
            gridBeneath: false,
            gridOnTop: true,
            standbyReasonId: '',
            standbyReasonName: '',
            comments: '',
            status: 'draft' as const,
            totalSy: 556,
            totalNetSy: 11250,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            createdBy: 'John Smith',
        },
    ];
    localStorage.setItem('ifi_material_usage_logs', JSON.stringify(sampleMaterialUsageLogs));

    // Create sample Issues Logs
    const sampleIssuesLogs = [
        {
            id: generateId(),
            projectId: SAMPLE_IDS.la106,
            projectName: 'LA 106 Phase 3',
            date: '2025-11-19',
            time: '10:30',
            issueTypeId: SAMPLE_LOOKUP_VALUES.issue_types[0].id,
            issueTypeName: 'Weather Delay',
            flag: 'normal' as const,
            description: 'Light rain starting at 10:00 AM. Paused operations until weather cleared.',
            temperature: 65,
            hasRain: true,
            rainDuration: '2 hours',
            hasPlantBreakdown: false,
            plantBreakdownDuration: '',
            photos: [],
            reportedById: SAMPLE_IDS.barryBoothe,
            reportedByName: 'Barry Boothe',
            notes: 'Resumed work at 12:30 PM after conditions improved.',
            status: 'approved' as const,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: generateId(),
            projectId: SAMPLE_IDS.us62,
            projectName: 'US 62 Seagraves',
            date: '2025-12-21',
            time: '14:15',
            issueTypeId: SAMPLE_LOOKUP_VALUES.issue_types[1].id,
            issueTypeName: 'Equipment Issue',
            flag: 'urgent' as const,
            description: 'Lay down machine hydraulic leak. Requires immediate repair.',
            temperature: null,
            hasRain: false,
            rainDuration: '',
            hasPlantBreakdown: true,
            plantBreakdownDuration: '3 hours',
            photos: [],
            reportedById: SAMPLE_IDS.mikeWilson,
            reportedByName: 'Mike Wilson',
            notes: 'Mechanic dispatched. Waiting for parts.',
            status: 'pending' as const,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];
    localStorage.setItem('ifi_issues_logs', JSON.stringify(sampleIssuesLogs));

    // Create sample Daily Field Reports
    const sampleDailyReports: any[] = [];
    localStorage.setItem('ifi_daily_field_reports', JSON.stringify(sampleDailyReports));

    // Create sample JHA Forms
    const sampleJHAs = [
        {
            id: generateId(),
            projectId: SAMPLE_IDS.la106,
            projectName: 'LA 106 Phase 3',
            date: '2025-11-18',
            tasks: [
                { id: '1', name: 'Traffic Control', hazards: 'Moving traffic', controls: 'Vests, Cones, Signs', riskLevel: 'High' },
                { id: '2', name: 'Material Handling', hazards: 'Lifting strain, pinch points', controls: 'Team lift, gloves', riskLevel: 'Medium' },
                { id: '3', name: 'Tack Coat Application', hazards: 'Hot material, fumes', controls: 'PPE, ventilator if needed', riskLevel: 'Medium' },
                { id: '4', name: 'Grid Installation', hazards: 'Tripping, cuts', controls: 'Clear path, gloves, utility knife safety', riskLevel: 'Low' },
            ],
            ppe: ['Hard Hat', 'Safety Vest', 'Steel Toe Boots', 'Gloves', 'Safety Glasses'],
            weather: 'Clear, 75F',
            notes: 'Toolbox talk conducted at 7:00 AM.',
            signatures: [],
            status: 'submitted' as const,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            createdBy: 'Barry Boothe',
        }
    ];
    localStorage.setItem('ifi_jha_forms', JSON.stringify(sampleJHAs));

    // Create sample Pre-Construction Checklists
    const samplePCC = [
        {
            id: generateId(),
            formNumber: 'PCC-20251117-001',
            projectId: SAMPLE_IDS.la106,
            projectName: 'LA 106 Phase 3',
            epNumber: 'EP-2024-001',
            projectTeam: [SAMPLE_IDS.barryBoothe, SAMPLE_IDS.paigeLandrum],
            projectTeamNames: ['Barry Boothe', 'Paige Landrum'],
            salesPerson: [SAMPLE_IDS.barryBoothe],
            salesPersonNames: ['Barry Boothe'],
            contractor: 'Gilchrist Construction',
            contractorId: SAMPLE_IDS.gilchrist,
            superintendentName: 'Dirk Fontenot',
            superintendentPhone: '(318) 715-7302',
            superintendentEmail: 'dfontenot@gilchrist.com',
            projectAddress: 'LA 106, Crowley, LA',
            specialInstructions: 'Coordinate with DOTD for lane closures. Work in 1-mile segments.',
            projectType: 'State' as const,
            projectTypeOther: '',
            dayTime: true,
            nightTime: false,
            rubberTireNotification: true,
            plansReviewedById: SAMPLE_IDS.barryBoothe,
            plansReviewedByName: 'Barry Boothe',
            submittals: 'Approved' as const,
            contractNumber: 'H-01569',
            estimatedStartDate: '2025-11-17',
            estimatedDuration: '3 DAYS',
            equipmentOnSiteDate: '2025-11-16',
            materials: [],
            cutRollsRequired: false,
            cutRollSize: '',
            cutRollQty: 0,
            extensionBarsRequired: false,
            warehouse: 'baton_rouge',
            projectSY: 11693,
            surfaceTypes: [
                { type: 'Milled' as const, selected: true, rate: 0.2, gallons: 2339, lbs: 18709 },
                { type: 'Levelup' as const, selected: false, rate: 0.15, gallons: 0, lbs: 0 },
                { type: 'Seal Coat' as const, selected: false, rate: 0.23, gallons: 0, lbs: 0 },
            ],
            tackCoatTypes: ['Jebro'],
            oilSource: 'ifi_sprays_supplies',
            oilCompany: 'R&D',
            oilAddress: '',
            oilBusHrs: '',
            oilPULoad: '',
            oilPOIFI: '',
            oilContact1: '',
            oilContact2: '',
            tractorType: 'Kubota with no rollers' as const,
            numTractors: 1,
            trailerUnit: 'T-101',
            tractorUnit: 'K-203',
            backpackBlowers: true,
            gasBlower4Wheeler: false,
            pipeLengths: ['pipe_12.5'],
            otherItems: ['core_pullers', 'tire_chemical', 'new_brushes'],
            vanTruckType: 'penske_26',
            truckInspection: Array(15).fill(null).map((_, i) => ({ id: generateId(), label: `Truck item ${i + 1}`, checked: true })),
            trailerInspection: Array(8).fill(null).map((_, i) => ({ id: generateId(), label: `Trailer item ${i + 1}`, checked: true })),
            miscEquipment: Array(28).fill(null).map((_, i) => ({ id: generateId(), label: `Misc item ${i + 1}`, checked: true })),
            equipmentTractorType: 'Kubota with no rollers',
            equipmentNumTractors: 1,
            equipmentPipeLengths: ['pipe_12.5'],
            completedById: SAMPLE_IDS.barryBoothe,
            completedByName: 'Barry Boothe',
            dateCompleted: '2025-11-05',
            dateSentToErnesto: '2025-11-05',
            dateSentToBobby: '2025-11-05',
            signature: '',
            status: 'approved' as const,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            createdBy: 'system',
        },
    ];
    localStorage.setItem('ifi_preconstruction_checklists', JSON.stringify(samplePCC));

    console.log('Sample data initialized successfully!');
}

// Reset all data and reload sample data
export function resetAllData() {
    initializeSampleData(true);
    window.location.reload();
}
